### ISSUE TITLE
Syntax warning after generating ...

### ISSUE THREAD

**Issue by SanwebGit** [teeks99/weewx-json#12]
Hello,

at first thank you very much for spending your time to provide us this very nice plugin.

Today i install your plugin in my weewx 5.0.2 installtion and it works fine, but when weewx generate die json files, i can see this in my log:

> Feb 24 01:45:41 weewxd[1137880]: _etc_weewx_skins_JSON_weewx_json_tmpl.py:113: SyntaxWarning: "is" with a literal. Did you mean "=="?
> Feb 24 01:45:41 weewxd[1137880]: _etc_weewx_skins_JSON_current_minimal_json_tmpl.py:113: SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by vinceskahan** [comment]
Changing 'is' to '==' seems to do the right thing.  Tested on macos vs. weewx 5.1.0
(and thanks for the nice skin!)
