### ISSUE TITLE
Odd output in max and mins?

### ISSUE THREAD

**Issue by digitalurban** [teeks99/weewx-json#6]
Morning - i am getting extra characters in the max/min output - see below. My data seem fine - reporting at http://www.finchamweather.co.uk/weewx/

Any idea? 

    "day": {
        "outTemp": {
            "max": "13.1 &#176;C",
            "maxtime": "10:55:34",
            "min": "9.2 &#176;C",
            "mintime": "06:22:03"
        },
        "appTemp": {
            "max": "12.2 &#176;C",
            "maxtime": "10:49:41",
            "min": "5.0 &#176;C",
            "mintime": "04:57:41"
        },
        "heatindex": {
            "max": "12.8 &#176;C",
            "maxtime": "10:55:34"
        },
        "windchill": {
            "max": "6.5 &#176;C",
            "maxtime": "06:31:31"
        },
        "humidity": {
            "max": "96%",
            "maxtime": "06:37:35",
            "min": "89%",
            "mintime": "10:37:19"
        },
        "dewpoint": {
            "max": "11.5 &#176;C",
            "maxtime": "10:49:37",
            "min": "8.2 &#176;C",
            "mintime": "01:34:40"
        },
        "barometer": {
            "max": "1027.2 mbar",
            "maxtime": "00:00:01",
            "min": "1023.7 mbar",
            "mintime": "09:10:01"
        },
        "wind": {
            "max": "15 mph",
            "maxtime": "10:33:39",
            "gustdir": "288&#176;",
            "average": "5 mph",
            "vectordir": "272&#176;",
            "vectoravg": "5 mph",
            "windrun_max": "6.4 km",
            "windrun_maxtime": "10:30:00",
            "windrun_min": "2.4 km",
            "windrun_mintime": "00:30:00",
            "rms": "6 mph"
        },
        "uv": {
            "max": "0.9",
            "maxtime": "10:22:59",
            "min": "0.0",
            "mintime": "00:00:01"
        },
        "solar_radiation": {
            "max": "207 W/m&#178;",
            "maxtime": "10:23:41",
            "min": "0 W/m&#178;",
            "mintime": "00:00:01"
        },
        "rain": {
            "sum": "0.0 mm",
            "max": "0.0 mm/hr",
            "maxtime": "00:00:01"
        }
    },
    
    "week": {
        "outTemp": {
            "max": "16.6 &#176;C",
            "maxtime": "14:14:37 (Sunday)",
            "min": "6.4 &#176;C",
            "mintime": "07:15:27 (Monday)"
        },
        "appTemp": {
            "max": "16.7 &#176;C",
            "maxtime": "14:07:45 (Sunday)",
            "min": "3.1 &#176;C",
            "mintime": "06:02:19 (Monday)"
        },
        "heatindex": {
            "max": "16.5 &#176;C",
            "maxtime": "14:14:37 (Sunday)"
        },
        "windchill": {
            "max": "4.0 &#176;C",
            "maxtime": "06:02:19 (Monday)"
        },
        "humidity": {
            "max": "99%",
            "maxtime": "04:17:48 (Sunday)",
            "min": "73%",
            "mintime": "14:14:02 (Monday)"
        },
        "dewpoint": {
            "max": "14.5 &#176;C",
            "maxtime": "10:53:53 (Sunday)",
            "min": "5.9 &#176;C",
            "mintime": "07:15:27 (Monday)"
        },
        "barometer": {
            "max": "1031.0 mbar",
            "maxtime": "10:33:01 (Monday)",
            "min": "1023.7 mbar",
            "mintime": "09:10:01 (Tuesday)"
        },
        "wind": {
            "max": "16 mph",
            "maxtime": "13:41:26 (Monday)",
            "gustdir": "323&#176;",
            "average": "4 mph",
            "vectordir": "290&#176;",
            "vectoravg": "3 mph",
            "windrun_max": "8.0 km",
            "windrun_maxtime": "14:00:00 (Monday)",
            "windrun_min": "0.0 km",
            "windrun_mintime": "00:30:00 (Sunday)",
            "rms": "5 mph"
        },
        "uv": {
            "max": "1.4",
            "maxtime": "12:41:29 (Sunday)",
            "min": "0.0",
            "mintime": "00:00:01 (Sunday)"
        },
        "solar_radiation": {
            "max": "404 W/m&#178;",
            "maxtime": "14:56:03 (Sunday)",
            "min": "0 W/m&#178;",
            "mintime": "00:00:01 (Sunday)"
        },
        "rain": {
            "sum": "0.2 mm",
            "max": "0.0 mm/hr",
            "maxtime": "00:00:01 (Sunday)"
        } 
    },
    
    "month": {
        "outTemp": {
            "max": "19.8 &#176;C",
            "maxtime": "07/10/21 14:32:25",
            "min": "6.1 &#176;C",
            "mintime": "02/10/21 01:38:10"
        },
        "appTemp": {
            "max": "21.8 &#176;C",
            "maxtime": "07/10/21 14:24:47",
            "min": "0.3 &#176;C",
            "mintime": "06/10/21 05:40:49"
        },
        "heatindex": {
            "max": "20.0 &#176;C",
            "maxtime": "07/10/21 14:32:25"
        },
        "windchill": {
            "max": "4.0 &#176;C",
            "maxtime": "11/10/21 06:02:19"
        },
        "humidity": {
            "max": "99%",
            "maxtime": "08/10/21 02:53:22",
            "min": "62%",
            "mintime": "01/10/21 16:43:08"
        },
        "dewpoint": {
            "max": "16.7 &#176;C",
            "maxtime": "07/10/21 14:56:45",
            "min": "4.6 &#176;C",
            "mintime": "02/10/21 01:28:34"
        },
        "barometer": {
            "max": "1031.0 mbar",
            "maxtime": "11/10/21 10:33:01",
            "min": "983.2 mbar",
            "mintime": "02/10/21 20:34:02"
        },
        "wind": {
            "max": "32 mph",
            "maxtime": "05/10/21 20:53:51",
            "gustdir": "250&#176;",
            "average": "4 mph",
            "vectordir": "222&#176;",
            "vectoravg": "1 mph",
            "windrun_max": "11.3 km",
            "windrun_maxtime": "06/10/21 06:00:00",
            "windrun_min": "0.0 km",
            "windrun_mintime": "01/10/21 19:30:00",
            "rms": "5 mph"
        },
        "uv": {
            "max": "1.9",
            "maxtime": "01/10/21 14:41:09",
            "min": "0.0",
            "mintime": "01/10/21 00:00:05"
        },
        "solar_radiation": {
            "max": "656 W/m&#178;",
            "maxtime": "01/10/21 14:41:51",
            "min": "0 W/m&#178;",
            "mintime": "01/10/21 00:00:05"
        },
        "rain": {
            "sum": "32.6 mm",
            "max": "13107.0 mm/hr",
            "maxtime": "05/10/21 19:00:03"
        }
    },
    
    "year": {
        "outTemp": {
            "max": "31.0 &#176;C",
            "maxtime": "18/07/21 16:50:59",
            "min": "6.1 &#176;C",
            "mintime": "30/09/21 04:35:42"
        },
        "appTemp": {
            "max": "34.3 &#176;C",
            "maxtime": "18/07/21 16:42:13",
            "min": "0.3 &#176;C",
            "mintime": "06/10/21 05:40:49"
        },
        "heatindex": {
            "max": "32.8 &#176;C",
            "maxtime": "18/07/21 16:52:21"
        },
        "windchill": {
            "max": "3.7 &#176;C",
            "maxtime": "30/09/21 05:06:06"
        },
        "humidity": {
            "max": "99%",
            "maxtime": "13/07/21 06:54:01",
            "min": "39%",
            "mintime": "08/09/21 15:47:52"
        },
        "dewpoint": {
            "max": "22.1 &#176;C",
            "maxtime": "21/07/21 14:55:52",
            "min": "4.6 &#176;C",
            "mintime": "30/09/21 04:35:42"
        },
        "barometer": {
            "max": "1032.4 mbar",
            "maxtime": "31/08/21 23:35:04",
            "min": "983.2 mbar",
            "mintime": "02/10/21 20:34:02"
        },
        "wind": {
            "max": "32 mph",
            "maxtime": "05/10/21 20:53:51",
            "gustdir": "250&#176;",
            "average": "3 mph",
            "vectordir": "320&#176;",
            "vectoravg": "1 mph",
            "windrun_max": "11.3 km",
            "windrun_maxtime": "06/10/21 06:00:00",
            "windrun_min": "0.0 km",
            "windrun_mintime": "09/07/21 20:30:00",
            "rms": "4 mph"
        },
        "uv": {
            "max": "6.9",
            "maxtime": "10/07/21 13:20:23",
            "min": "0.0",
            "mintime": "09/07/21 18:42:58"
        },
        "solar_radiation": {
            "max": "1157 W/m&#178;",
            "maxtime": "10/07/21 13:22:49",
            "min": "0 W/m&#178;",
            "mintime": "09/07/21 20:51:24"
        },
        "rain": {
            "sum": "214.8 mm",
            "max": "13107.0 mm/hr",
            "maxtime": "18/07/21 06:30:00"
        }
    },
    "almanac": {
        "sunrise": "07:17:36",
        "sunrise_epoch": "1634019456",
        "sunrise_hour": "07",
        "sunrise_minute": "17",
        "sunset": "18:12:39",
        "sunset_epoch": "1634058759",
        "sunset_hour": "18",
        "sunset_minute": "12",
        "moon": {
            "moon_fullness": "35",
            "moon_phase": "First quarter",
            "moon_index": "2"
        }
    }
}

**Comment by teeks99** [comment]
This doesn't seem like you're using the package from this repo. The output looks different from what is being done here. 

In the weewx-json package the units are split from the value such as:
`"temperature": {"value": 55.0, "units": "°F"},`

Also, the `&#176;` stuff that you're seeing in a lot of places is the encoded format of the `°` symbol. At [my station](https://w.teeks99.com/weewx.json), those symbols are encoded correctly.  It looks like the plugin that is outputting your json is encoding the UTF-8 to ASCII bytes (a very common thing to do).

**Comment by digitalurban** [comment]
Well that's embarrassing - you're right - now installed the current repo and its working :) thanks for the reply 👍

**Comment by teeks99** [comment]
No worries.
