### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 42willow** [teeks99/weewx-json#8]
When I run: `wee_extension --install=weewx-json_1.1.tar.gz` it throws this error: `FileNotFoundError: [Errno 2] No such file or directory: '/etc/weewx/skins/JSON/current_minimal.json.tmpl'` am I doing something wrong?

**Comment by Zwilrich** [comment]
Put sudo in front of the command: **sudo wee_extension --install=weewx-json_1.1.tar.gz**
The skins folder is owned by root and an ordinary user can't write files there.

**Comment by 42willow** [comment]
Thank you, this works :)
